### ISSUE TITLE
Crash when clicking on the mod in Mods page

### ISSUE THREAD

**Issue by aaronhowser1** [Compressium/Compressium#33]
Crash: https://pastebin.com/NDpVJ8Xs

When clicking this:
![image](https://user-images.githubusercontent.com/15698722/129609085-90229cf3-378e-4393-a6ad-858ca7243e44.png)

This is playing FTB University 1.16, the mod version is Compressium-1.16.5-1.2.2

**Comment by DinnerBeef** [comment]
fixed uploading to curseforge. seems like have no logo file breaks stuff

**Comment by DinnerBeef** [comment]
will be on curseforge once the site comes back up
