### ISSUE TITLE
[Suggestion] Common mod-added metals

### ISSUE THREAD

**Issue by AbacusOperator** [Compressium/Compressium#34]
Can you please add (maybe in form of addon) compressed versions of storage blocks for metals frequently added by mods:
- Copper (for versions below 1.17)
- Lead
- Tin
- Zinc
- Nickel
- Silver

Also common alloys:
- Brass
- Bronze
- Steel
- Electrum

**Comment by DinnerBeef** [comment]
dont have any plans to add modded blocks ATM. might do it at some point.
